import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/profile-pic-2.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import UIUC from '../../public/images/pngs/uiuc.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>TAKEMiuL</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/3'>
              <Image src={profilePic} alt='takemiul' className='w-full h-auto' />
            </div>
            <div className='w-3/5 flex-col items-center self-center'>
              <AnimatedText text="Coder UIUCer Amazonian" className='!text-6xl !text-left' />
              <p className='my-4 text-base font-medium'>
              Let’s explore how we can collaborate!
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/resume.pdf" target='_blank'
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                '
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} /></Link>
                <Link href="mailto:tiluan1999@hotmail.com" target='_blank'
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <div className='absolute right-8 bottom-4 inline-block w-36'>
          <Image src={UIUC} alt='UIUC' className='w-full h-auto' />
        </div>
        
      </main>
    </>
  )
}
